package com.masterclass.auth.common.api;

public enum ErrorCode {
    EMAIL_ALREADY_IN_USE,
    USER_NOT_FOUND,
    INVALID_CREDENTIALS,
    VALIDATION_ERROR,
    INTERNAL_ERROR,
    AUTHENTICATION_FAILED,
    INVALID_REFRESH_TOKEN,
    REFRESH_TOKEN_EXPIRED
}